import { Inter } from "next/font/google";

import NavDashboard from "./dashboardNav/NavDashboard";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">


      <body className={`${inter.className} bg-[#F9F8FA] py-10`}>
        <NavDashboard />
        {children}</body>
    </html>
  );
}


