import { Providers } from "@/redux/app/Provider";
import NavBar from "@/sections/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
